defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

testing:
  do_test: False
  test_file: /mnt/CRAI-NAS/all/martinsr/test_monai/WMHSEG_0.5/outputs/2022-05-09/23-35-18/valdatasplit.txt

data:
  path: "data_test"
  # path: "/mnt/HDD1TB/martinsr/alldata2"
  workers: 0
model:
  weights: "weights/wmh_model_unique_data.pth"
  fazekas_weight: "weights/classification_model_v04.pickle"
  modeltype: "UNET"
