defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .


testing:
  do_test: False
  test_file: /mnt/CRAI-NAS/all/martinsr/test_monai/WMHSEG_0.5/outputs/2022-05-09/23-35-18/valdatasplit.txt

data:
  path: "/mnt/HDD16TB/martinsr/DatasetWMH211018_v2/test_sample"
  # path: "/mnt/HDD18TB/martinsr/alldata2"
  workers: 0
  filename: FLAIR.nii.gz
  outputmaskname: F_seg_testseg
model:
  weights: "weights/wmh_modelweights_12_05_2022.pth"

