defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

testing:
  do_test: False
  test_file: /workspace/outputs/2022-05-09/23-35-18/valdatasplit.txt

data:
  path: "/workspace/alldata"
  workers: 0
  filename: FLAIR.nii.gz
  outputmaskname: F_seg
model:
  weights: "/workspace/2_5DSEG_PRED/console_version/weights/wmh_modelweights_12_05_2022.pth"

gpu:
  device_pin: 0
