structure:
  model: UNET
  val_interval: 1
  weights: ../../../saved_models/best_metric_model_labelmentation2d_dict_ORTHOGONAL_ROTATED.pth
  optimweights: /mnt/CRAI-NAS/all/martinsr/test_monai/WMHSEG_0.1/best_metric_model_labelmentation2d_dict_optim.pth
  loadweights: False
  loadoptim: False
  train_patient_batch_size: 5
  validation_patient_batch_size: 5
  findLR: False
  all_orientations: True
  include_fazekas: False

hardware:
    gpu: cuda:0

datasets:
    trainfolder: /mnt/HDD16TB/martinsr/DatasetWMH211018_v2/train
    valfolder: /mnt/HDD16TB/martinsr/DatasetWMH211018_v2/val

hyperparams:
  lr: 1e-4
  epochs: 250
  gamma: 1.333 # 4/3 -> 1.333
  alpha: 0.85
  beta: 0.15
  smoothing: 1
  gradclip: 4
  batch_accumulation: 1

augmentations:
  mixup: False
  alpha: 0.4

scheduelerparams:
  factor: 0.2
  patience: 2


# /saved_models/D2021_03_31T17_20_20_872806_FLAIR_85_tripple_mish_aug_axial_fixednewdata/best_params.pt