structure:
  model: UNET
  val_interval: 1
  weights: /mnt/CRAI-NAS/all/martinsr/test_monai/WMHSEG_0.5/outputs/2022-10-17/12-49-49/best_metric_model_labelmentation2d_dict.pth
  optimweights: /mnt/CRAI-NAS/all/martinsr/test_monai/WMHSEG_0.5/outputs/2022-10-17/12-49-49/best_metric_model_labelmentation2d_dict_optim.pth
  loadweights: True
  loadoptim: True
  mini_batch_size: 8
  train_patient_batch_size: 3
  validation_patient_batch_size: 3
  findLR: False
  all_orientations: True
hardware:
  gpu: cuda:0

datasets:
  trainfolder: /mnt/HDD16TB/martinsr/DatasetWMH211018_v2/train
  valfolder: /mnt/HDD16TB/martinsr/DatasetWMH211018_v2/val
  datafolder: /mnt/HDD16TB/martinsr/DatasetWMH211018_v2/alldata
  # datafolder: /mnt/HDD18TB/martinsr/alldata2
  datasplit_test: 0.1
  datasplit_val: 0.2
  presplit: False
  presplit_path: /mnt/CRAI-NAS/all/martinsr/test_monai/WMHSEG_0.5/outputs/2022-05-09/13-01-13

hyperparams:
  lr: 1e-4
  epochs: 60
  gamma: 1.333 # 4/3
  alpha: 0.85
  beta: 0.15
  smoothing: 1
  gradclip: 4
  batch_accumulation: 1

augmentations:
  mixup: False
  alpha: 0.4

scheduelerparams:
  factor: 0.2
  patience: 2
# /saved_models/D2021_03_31T17_20_20_872806_FLAIR_85_tripple_mish_aug_axial_fixednewdata/best_params.pt
